// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.services.service2;

public interface ScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.service2.Schedule schedule = 3;</code>
   * @return Whether the schedule field is set.
   */
  boolean hasSchedule();
  /**
   * <code>.service2.Schedule schedule = 3;</code>
   * @return The schedule.
   */
  grpc.services.service2.Schedule getSchedule();
  /**
   * <code>.service2.Schedule schedule = 3;</code>
   */
  grpc.services.service2.ScheduleOrBuilder getScheduleOrBuilder();
}
