// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.services.service2;

public interface ScheduleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Schedule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string position = 2;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 2;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string startTime = 4;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string startTime = 4;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string endTime = 5;</code>
   */
  java.lang.String getEndTime();
  /**
   * <code>string endTime = 5;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();
}
