// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface AvailableTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AvailableTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string start_time = 1;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string end_time = 2;</code>
   */
  java.lang.String getEndTime();
  /**
   * <code>string end_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();
}
