// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface AvailableStaffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AvailableStaffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .service3.AvailableTime available_times = 2;</code>
   */
  java.util.List<grpc.services.service3.AvailableTime> 
      getAvailableTimesList();
  /**
   * <code>repeated .service3.AvailableTime available_times = 2;</code>
   */
  grpc.services.service3.AvailableTime getAvailableTimes(int index);
  /**
   * <code>repeated .service3.AvailableTime available_times = 2;</code>
   */
  int getAvailableTimesCount();
  /**
   * <code>repeated .service3.AvailableTime available_times = 2;</code>
   */
  java.util.List<? extends grpc.services.service3.AvailableTimeOrBuilder> 
      getAvailableTimesOrBuilderList();
  /**
   * <code>repeated .service3.AvailableTime available_times = 2;</code>
   */
  grpc.services.service3.AvailableTimeOrBuilder getAvailableTimesOrBuilder(
      int index);
}
