// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface AvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string position = 2;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 2;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
