// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface AvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_available = 1;</code>
   */
  boolean getIsAvailable();

  /**
   * <code>int32 working_hours = 2;</code>
   */
  int getWorkingHours();
}
