// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_StaffSchedule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_StaffSchedule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"C\n\023Availabili" +
      "tyRequest\022\014\n\004date\030\001 \001(\t\022\020\n\010position\030\002 \001(" +
      "\t\022\014\n\004name\030\003 \001(\t\"C\n\024AvailabilityResponse\022" +
      "\024\n\014is_available\030\001 \001(\010\022\025\n\rworking_hours\030\002" +
      " \001(\005\"@\n\rUpdateRequest\022/\n\016staff_schedule\030" +
      "\001 \001(\0132\027.service3.StaffSchedule\"U\n\016Update" +
      "Response\022\022\n\nis_updated\030\001 \001(\010\022/\n\016staff_sc" +
      "hedule\030\002 \001(\0132\027.service3.StaffSchedule\"0\n" +
      "\rStaffSchedule\022\r\n\005staff\030\001 \001(\t\022\020\n\010schedul" +
      "e\030\002 \001(\t2\270\001\n\021StaffAvailability\022X\n\021CheckAv" +
      "ailability\022\035.service3.AvailabilityReques" +
      "t\032\036.service3.AvailabilityResponse\"\000(\0010\001\022" +
      "I\n\016UpdateSchedule\022\027.service3.UpdateReque" +
      "st\032\030.service3.UpdateResponse\"\000(\0010\001B(\n\026gr" +
      "pc.services.service3B\014Service3ImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_AvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_AvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailabilityRequest_descriptor,
        new java.lang.String[] { "Date", "Position", "Name", });
    internal_static_service3_AvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_AvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailabilityResponse_descriptor,
        new java.lang.String[] { "IsAvailable", "WorkingHours", });
    internal_static_service3_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UpdateRequest_descriptor,
        new java.lang.String[] { "StaffSchedule", });
    internal_static_service3_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UpdateResponse_descriptor,
        new java.lang.String[] { "IsUpdated", "StaffSchedule", });
    internal_static_service3_StaffSchedule_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_StaffSchedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_StaffSchedule_descriptor,
        new java.lang.String[] { "Staff", "Schedule", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
