// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_StaffAvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_StaffAvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_StaffAvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_StaffAvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_StaffAvailabilityResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_StaffAvailabilityResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailableTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailableTime_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailableStaffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailableStaffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailableStaffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailableStaffResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"\256\001\n\030StaffAvai" +
      "labilityRequest\022\014\n\004date\030\001 \001(\t\022F\n\rsearch_" +
      "option\030\002 \001(\0162/.service3.StaffAvailabilit" +
      "yRequest.SearchOption\022\024\n\014search_input\030\003 " +
      "\001(\t\"&\n\014SearchOption\022\010\n\004NAME\020\000\022\014\n\010POSITIO" +
      "N\020\001\"O\n\031StaffAvailabilityResponse\0222\n\007resu" +
      "lts\030\001 \003(\0132!.service3.StaffAvailabilityRe" +
      "sult\"k\n\027StaffAvailabilityResult\022\014\n\004name\030" +
      "\001 \001(\t\022\020\n\010position\030\002 \001(\t\0220\n\017available_tim" +
      "es\030\003 \003(\0132\027.service3.AvailableTime\"5\n\rAva" +
      "ilableTime\022\022\n\nstart_time\030\001 \001(\t\022\020\n\010end_ti" +
      "me\030\002 \001(\t\"7\n\025AvailableStaffRequest\022\014\n\004dat" +
      "e\030\001 \001(\t\022\020\n\010position\030\002 \001(\t\"X\n\026AvailableSt" +
      "affResponse\022\014\n\004name\030\001 \001(\t\0220\n\017available_t" +
      "imes\030\002 \003(\0132\027.service3.AvailableTime2\327\001\n\026" +
      "StaffAvailabilityCheck\022a\n\024GetStaffAvaila" +
      "bility\022\".service3.StaffAvailabilityReque" +
      "st\032#.service3.StaffAvailabilityResponse\"" +
      "\000\022Z\n\021GetAvailableStaff\022\037.service3.Availa" +
      "bleStaffRequest\032 .service3.AvailableStaf" +
      "fResponse\"\0000\001B(\n\026grpc.services.service3B" +
      "\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_StaffAvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_StaffAvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_StaffAvailabilityRequest_descriptor,
        new java.lang.String[] { "Date", "SearchOption", "SearchInput", });
    internal_static_service3_StaffAvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_StaffAvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_StaffAvailabilityResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_service3_StaffAvailabilityResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_StaffAvailabilityResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_StaffAvailabilityResult_descriptor,
        new java.lang.String[] { "Name", "Position", "AvailableTimes", });
    internal_static_service3_AvailableTime_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_AvailableTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailableTime_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", });
    internal_static_service3_AvailableStaffRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_AvailableStaffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailableStaffRequest_descriptor,
        new java.lang.String[] { "Date", "Position", });
    internal_static_service3_AvailableStaffResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_AvailableStaffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailableStaffResponse_descriptor,
        new java.lang.String[] { "Name", "AvailableTimes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
