// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

/**
 * Protobuf type {@code service3.StaffAvailabilityRequest}
 */
public  final class StaffAvailabilityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.StaffAvailabilityRequest)
    StaffAvailabilityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StaffAvailabilityRequest.newBuilder() to construct.
  private StaffAvailabilityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StaffAvailabilityRequest() {
    date_ = "";
    searchOption_ = 0;
    searchInput_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StaffAvailabilityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            searchOption_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            searchInput_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.service3.StaffAvailabilityRequest.class, grpc.services.service3.StaffAvailabilityRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code service3.StaffAvailabilityRequest.SearchOption}
   */
  public enum SearchOption
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NAME = 0;</code>
     */
    NAME(0),
    /**
     * <code>POSITION = 1;</code>
     */
    POSITION(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NAME = 0;</code>
     */
    public static final int NAME_VALUE = 0;
    /**
     * <code>POSITION = 1;</code>
     */
    public static final int POSITION_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SearchOption valueOf(int value) {
      return forNumber(value);
    }

    public static SearchOption forNumber(int value) {
      switch (value) {
        case 0: return NAME;
        case 1: return POSITION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SearchOption>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SearchOption> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SearchOption>() {
            public SearchOption findValueByNumber(int number) {
              return SearchOption.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.services.service3.StaffAvailabilityRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final SearchOption[] VALUES = values();

    public static SearchOption valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SearchOption(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:service3.StaffAvailabilityRequest.SearchOption)
  }

  public static final int DATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object date_;
  /**
   * <code>string date = 1;</code>
   */
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEARCH_OPTION_FIELD_NUMBER = 2;
  private int searchOption_;
  /**
   * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
   */
  public int getSearchOptionValue() {
    return searchOption_;
  }
  /**
   * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
   */
  public grpc.services.service3.StaffAvailabilityRequest.SearchOption getSearchOption() {
    @SuppressWarnings("deprecation")
    grpc.services.service3.StaffAvailabilityRequest.SearchOption result = grpc.services.service3.StaffAvailabilityRequest.SearchOption.valueOf(searchOption_);
    return result == null ? grpc.services.service3.StaffAvailabilityRequest.SearchOption.UNRECOGNIZED : result;
  }

  public static final int SEARCH_INPUT_FIELD_NUMBER = 3;
  private volatile java.lang.Object searchInput_;
  /**
   * <code>string search_input = 3;</code>
   */
  public java.lang.String getSearchInput() {
    java.lang.Object ref = searchInput_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searchInput_ = s;
      return s;
    }
  }
  /**
   * <code>string search_input = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSearchInputBytes() {
    java.lang.Object ref = searchInput_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchInput_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
    }
    if (searchOption_ != grpc.services.service3.StaffAvailabilityRequest.SearchOption.NAME.getNumber()) {
      output.writeEnum(2, searchOption_);
    }
    if (!getSearchInputBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, searchInput_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
    }
    if (searchOption_ != grpc.services.service3.StaffAvailabilityRequest.SearchOption.NAME.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, searchOption_);
    }
    if (!getSearchInputBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, searchInput_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.service3.StaffAvailabilityRequest)) {
      return super.equals(obj);
    }
    grpc.services.service3.StaffAvailabilityRequest other = (grpc.services.service3.StaffAvailabilityRequest) obj;

    boolean result = true;
    result = result && getDate()
        .equals(other.getDate());
    result = result && searchOption_ == other.searchOption_;
    result = result && getSearchInput()
        .equals(other.getSearchInput());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + SEARCH_OPTION_FIELD_NUMBER;
    hash = (53 * hash) + searchOption_;
    hash = (37 * hash) + SEARCH_INPUT_FIELD_NUMBER;
    hash = (53 * hash) + getSearchInput().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.service3.StaffAvailabilityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.StaffAvailabilityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.StaffAvailabilityRequest)
      grpc.services.service3.StaffAvailabilityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.service3.StaffAvailabilityRequest.class, grpc.services.service3.StaffAvailabilityRequest.Builder.class);
    }

    // Construct using grpc.services.service3.StaffAvailabilityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      date_ = "";

      searchOption_ = 0;

      searchInput_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityRequest_descriptor;
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityRequest getDefaultInstanceForType() {
      return grpc.services.service3.StaffAvailabilityRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityRequest build() {
      grpc.services.service3.StaffAvailabilityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityRequest buildPartial() {
      grpc.services.service3.StaffAvailabilityRequest result = new grpc.services.service3.StaffAvailabilityRequest(this);
      result.date_ = date_;
      result.searchOption_ = searchOption_;
      result.searchInput_ = searchInput_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.service3.StaffAvailabilityRequest) {
        return mergeFrom((grpc.services.service3.StaffAvailabilityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.service3.StaffAvailabilityRequest other) {
      if (other == grpc.services.service3.StaffAvailabilityRequest.getDefaultInstance()) return this;
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      if (other.searchOption_ != 0) {
        setSearchOptionValue(other.getSearchOptionValue());
      }
      if (!other.getSearchInput().isEmpty()) {
        searchInput_ = other.searchInput_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.service3.StaffAvailabilityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.service3.StaffAvailabilityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }

    private int searchOption_ = 0;
    /**
     * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
     */
    public int getSearchOptionValue() {
      return searchOption_;
    }
    /**
     * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
     */
    public Builder setSearchOptionValue(int value) {
      searchOption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
     */
    public grpc.services.service3.StaffAvailabilityRequest.SearchOption getSearchOption() {
      @SuppressWarnings("deprecation")
      grpc.services.service3.StaffAvailabilityRequest.SearchOption result = grpc.services.service3.StaffAvailabilityRequest.SearchOption.valueOf(searchOption_);
      return result == null ? grpc.services.service3.StaffAvailabilityRequest.SearchOption.UNRECOGNIZED : result;
    }
    /**
     * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
     */
    public Builder setSearchOption(grpc.services.service3.StaffAvailabilityRequest.SearchOption value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      searchOption_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
     */
    public Builder clearSearchOption() {
      
      searchOption_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object searchInput_ = "";
    /**
     * <code>string search_input = 3;</code>
     */
    public java.lang.String getSearchInput() {
      java.lang.Object ref = searchInput_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchInput_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string search_input = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSearchInputBytes() {
      java.lang.Object ref = searchInput_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchInput_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string search_input = 3;</code>
     */
    public Builder setSearchInput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      searchInput_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string search_input = 3;</code>
     */
    public Builder clearSearchInput() {
      
      searchInput_ = getDefaultInstance().getSearchInput();
      onChanged();
      return this;
    }
    /**
     * <code>string search_input = 3;</code>
     */
    public Builder setSearchInputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      searchInput_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.StaffAvailabilityRequest)
  }

  // @@protoc_insertion_point(class_scope:service3.StaffAvailabilityRequest)
  private static final grpc.services.service3.StaffAvailabilityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.service3.StaffAvailabilityRequest();
  }

  public static grpc.services.service3.StaffAvailabilityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StaffAvailabilityRequest>
      PARSER = new com.google.protobuf.AbstractParser<StaffAvailabilityRequest>() {
    @java.lang.Override
    public StaffAvailabilityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StaffAvailabilityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StaffAvailabilityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StaffAvailabilityRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.service3.StaffAvailabilityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

