// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface StaffAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.StaffAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
   */
  int getSearchOptionValue();
  /**
   * <code>.service3.StaffAvailabilityRequest.SearchOption search_option = 2;</code>
   */
  grpc.services.service3.StaffAvailabilityRequest.SearchOption getSearchOption();

  /**
   * <code>string search_input = 3;</code>
   */
  java.lang.String getSearchInput();
  /**
   * <code>string search_input = 3;</code>
   */
  com.google.protobuf.ByteString
      getSearchInputBytes();
}
