// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface StaffAvailabilityResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.StaffAvailabilityResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string position = 2;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 2;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  java.util.List<grpc.services.service3.AvailableTime> 
      getAvailableTimesList();
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  grpc.services.service3.AvailableTime getAvailableTimes(int index);
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  int getAvailableTimesCount();
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  java.util.List<? extends grpc.services.service3.AvailableTimeOrBuilder> 
      getAvailableTimesOrBuilderList();
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  grpc.services.service3.AvailableTimeOrBuilder getAvailableTimesOrBuilder(
      int index);
}
