// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

/**
 * Protobuf type {@code service3.StaffAvailabilityResult}
 */
public  final class StaffAvailabilityResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.StaffAvailabilityResult)
    StaffAvailabilityResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StaffAvailabilityResult.newBuilder() to construct.
  private StaffAvailabilityResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StaffAvailabilityResult() {
    name_ = "";
    position_ = "";
    availableTimes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StaffAvailabilityResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            position_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              availableTimes_ = new java.util.ArrayList<grpc.services.service3.AvailableTime>();
              mutable_bitField0_ |= 0x00000004;
            }
            availableTimes_.add(
                input.readMessage(grpc.services.service3.AvailableTime.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        availableTimes_ = java.util.Collections.unmodifiableList(availableTimes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.service3.StaffAvailabilityResult.class, grpc.services.service3.StaffAvailabilityResult.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private volatile java.lang.Object position_;
  /**
   * <code>string position = 2;</code>
   */
  public java.lang.String getPosition() {
    java.lang.Object ref = position_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      position_ = s;
      return s;
    }
  }
  /**
   * <code>string position = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPositionBytes() {
    java.lang.Object ref = position_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      position_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLE_TIMES_FIELD_NUMBER = 3;
  private java.util.List<grpc.services.service3.AvailableTime> availableTimes_;
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  public java.util.List<grpc.services.service3.AvailableTime> getAvailableTimesList() {
    return availableTimes_;
  }
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  public java.util.List<? extends grpc.services.service3.AvailableTimeOrBuilder> 
      getAvailableTimesOrBuilderList() {
    return availableTimes_;
  }
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  public int getAvailableTimesCount() {
    return availableTimes_.size();
  }
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  public grpc.services.service3.AvailableTime getAvailableTimes(int index) {
    return availableTimes_.get(index);
  }
  /**
   * <code>repeated .service3.AvailableTime available_times = 3;</code>
   */
  public grpc.services.service3.AvailableTimeOrBuilder getAvailableTimesOrBuilder(
      int index) {
    return availableTimes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getPositionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, position_);
    }
    for (int i = 0; i < availableTimes_.size(); i++) {
      output.writeMessage(3, availableTimes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getPositionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, position_);
    }
    for (int i = 0; i < availableTimes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, availableTimes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.service3.StaffAvailabilityResult)) {
      return super.equals(obj);
    }
    grpc.services.service3.StaffAvailabilityResult other = (grpc.services.service3.StaffAvailabilityResult) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getPosition()
        .equals(other.getPosition());
    result = result && getAvailableTimesList()
        .equals(other.getAvailableTimesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition().hashCode();
    if (getAvailableTimesCount() > 0) {
      hash = (37 * hash) + AVAILABLE_TIMES_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableTimesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.StaffAvailabilityResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.service3.StaffAvailabilityResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.StaffAvailabilityResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.StaffAvailabilityResult)
      grpc.services.service3.StaffAvailabilityResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.service3.StaffAvailabilityResult.class, grpc.services.service3.StaffAvailabilityResult.Builder.class);
    }

    // Construct using grpc.services.service3.StaffAvailabilityResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAvailableTimesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      position_ = "";

      if (availableTimesBuilder_ == null) {
        availableTimes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        availableTimesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.service3.Service3Impl.internal_static_service3_StaffAvailabilityResult_descriptor;
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityResult getDefaultInstanceForType() {
      return grpc.services.service3.StaffAvailabilityResult.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityResult build() {
      grpc.services.service3.StaffAvailabilityResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.service3.StaffAvailabilityResult buildPartial() {
      grpc.services.service3.StaffAvailabilityResult result = new grpc.services.service3.StaffAvailabilityResult(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.position_ = position_;
      if (availableTimesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          availableTimes_ = java.util.Collections.unmodifiableList(availableTimes_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.availableTimes_ = availableTimes_;
      } else {
        result.availableTimes_ = availableTimesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.service3.StaffAvailabilityResult) {
        return mergeFrom((grpc.services.service3.StaffAvailabilityResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.service3.StaffAvailabilityResult other) {
      if (other == grpc.services.service3.StaffAvailabilityResult.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getPosition().isEmpty()) {
        position_ = other.position_;
        onChanged();
      }
      if (availableTimesBuilder_ == null) {
        if (!other.availableTimes_.isEmpty()) {
          if (availableTimes_.isEmpty()) {
            availableTimes_ = other.availableTimes_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAvailableTimesIsMutable();
            availableTimes_.addAll(other.availableTimes_);
          }
          onChanged();
        }
      } else {
        if (!other.availableTimes_.isEmpty()) {
          if (availableTimesBuilder_.isEmpty()) {
            availableTimesBuilder_.dispose();
            availableTimesBuilder_ = null;
            availableTimes_ = other.availableTimes_;
            bitField0_ = (bitField0_ & ~0x00000004);
            availableTimesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAvailableTimesFieldBuilder() : null;
          } else {
            availableTimesBuilder_.addAllMessages(other.availableTimes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.service3.StaffAvailabilityResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.service3.StaffAvailabilityResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object position_ = "";
    /**
     * <code>string position = 2;</code>
     */
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string position = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string position = 2;</code>
     */
    public Builder setPosition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string position = 2;</code>
     */
    public Builder clearPosition() {
      
      position_ = getDefaultInstance().getPosition();
      onChanged();
      return this;
    }
    /**
     * <code>string position = 2;</code>
     */
    public Builder setPositionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      position_ = value;
      onChanged();
      return this;
    }

    private java.util.List<grpc.services.service3.AvailableTime> availableTimes_ =
      java.util.Collections.emptyList();
    private void ensureAvailableTimesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        availableTimes_ = new java.util.ArrayList<grpc.services.service3.AvailableTime>(availableTimes_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.service3.AvailableTime, grpc.services.service3.AvailableTime.Builder, grpc.services.service3.AvailableTimeOrBuilder> availableTimesBuilder_;

    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public java.util.List<grpc.services.service3.AvailableTime> getAvailableTimesList() {
      if (availableTimesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(availableTimes_);
      } else {
        return availableTimesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public int getAvailableTimesCount() {
      if (availableTimesBuilder_ == null) {
        return availableTimes_.size();
      } else {
        return availableTimesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public grpc.services.service3.AvailableTime getAvailableTimes(int index) {
      if (availableTimesBuilder_ == null) {
        return availableTimes_.get(index);
      } else {
        return availableTimesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder setAvailableTimes(
        int index, grpc.services.service3.AvailableTime value) {
      if (availableTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailableTimesIsMutable();
        availableTimes_.set(index, value);
        onChanged();
      } else {
        availableTimesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder setAvailableTimes(
        int index, grpc.services.service3.AvailableTime.Builder builderForValue) {
      if (availableTimesBuilder_ == null) {
        ensureAvailableTimesIsMutable();
        availableTimes_.set(index, builderForValue.build());
        onChanged();
      } else {
        availableTimesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder addAvailableTimes(grpc.services.service3.AvailableTime value) {
      if (availableTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailableTimesIsMutable();
        availableTimes_.add(value);
        onChanged();
      } else {
        availableTimesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder addAvailableTimes(
        int index, grpc.services.service3.AvailableTime value) {
      if (availableTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailableTimesIsMutable();
        availableTimes_.add(index, value);
        onChanged();
      } else {
        availableTimesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder addAvailableTimes(
        grpc.services.service3.AvailableTime.Builder builderForValue) {
      if (availableTimesBuilder_ == null) {
        ensureAvailableTimesIsMutable();
        availableTimes_.add(builderForValue.build());
        onChanged();
      } else {
        availableTimesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder addAvailableTimes(
        int index, grpc.services.service3.AvailableTime.Builder builderForValue) {
      if (availableTimesBuilder_ == null) {
        ensureAvailableTimesIsMutable();
        availableTimes_.add(index, builderForValue.build());
        onChanged();
      } else {
        availableTimesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder addAllAvailableTimes(
        java.lang.Iterable<? extends grpc.services.service3.AvailableTime> values) {
      if (availableTimesBuilder_ == null) {
        ensureAvailableTimesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, availableTimes_);
        onChanged();
      } else {
        availableTimesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder clearAvailableTimes() {
      if (availableTimesBuilder_ == null) {
        availableTimes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        availableTimesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public Builder removeAvailableTimes(int index) {
      if (availableTimesBuilder_ == null) {
        ensureAvailableTimesIsMutable();
        availableTimes_.remove(index);
        onChanged();
      } else {
        availableTimesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public grpc.services.service3.AvailableTime.Builder getAvailableTimesBuilder(
        int index) {
      return getAvailableTimesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public grpc.services.service3.AvailableTimeOrBuilder getAvailableTimesOrBuilder(
        int index) {
      if (availableTimesBuilder_ == null) {
        return availableTimes_.get(index);  } else {
        return availableTimesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public java.util.List<? extends grpc.services.service3.AvailableTimeOrBuilder> 
         getAvailableTimesOrBuilderList() {
      if (availableTimesBuilder_ != null) {
        return availableTimesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(availableTimes_);
      }
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public grpc.services.service3.AvailableTime.Builder addAvailableTimesBuilder() {
      return getAvailableTimesFieldBuilder().addBuilder(
          grpc.services.service3.AvailableTime.getDefaultInstance());
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public grpc.services.service3.AvailableTime.Builder addAvailableTimesBuilder(
        int index) {
      return getAvailableTimesFieldBuilder().addBuilder(
          index, grpc.services.service3.AvailableTime.getDefaultInstance());
    }
    /**
     * <code>repeated .service3.AvailableTime available_times = 3;</code>
     */
    public java.util.List<grpc.services.service3.AvailableTime.Builder> 
         getAvailableTimesBuilderList() {
      return getAvailableTimesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.service3.AvailableTime, grpc.services.service3.AvailableTime.Builder, grpc.services.service3.AvailableTimeOrBuilder> 
        getAvailableTimesFieldBuilder() {
      if (availableTimesBuilder_ == null) {
        availableTimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.services.service3.AvailableTime, grpc.services.service3.AvailableTime.Builder, grpc.services.service3.AvailableTimeOrBuilder>(
                availableTimes_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        availableTimes_ = null;
      }
      return availableTimesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.StaffAvailabilityResult)
  }

  // @@protoc_insertion_point(class_scope:service3.StaffAvailabilityResult)
  private static final grpc.services.service3.StaffAvailabilityResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.service3.StaffAvailabilityResult();
  }

  public static grpc.services.service3.StaffAvailabilityResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StaffAvailabilityResult>
      PARSER = new com.google.protobuf.AbstractParser<StaffAvailabilityResult>() {
    @java.lang.Override
    public StaffAvailabilityResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StaffAvailabilityResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StaffAvailabilityResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StaffAvailabilityResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.service3.StaffAvailabilityResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

