// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface StaffScheduleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.StaffSchedule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string staff = 1;</code>
   */
  java.lang.String getStaff();
  /**
   * <code>string staff = 1;</code>
   */
  com.google.protobuf.ByteString
      getStaffBytes();

  /**
   * <code>string schedule = 2;</code>
   */
  java.lang.String getSchedule();
  /**
   * <code>string schedule = 2;</code>
   */
  com.google.protobuf.ByteString
      getScheduleBytes();
}
