// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface StaffAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.StaffAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .service3.StaffAvailabilityResult results = 1;</code>
   */
  java.util.List<grpc.services.service3.StaffAvailabilityResult> 
      getResultsList();
  /**
   * <code>repeated .service3.StaffAvailabilityResult results = 1;</code>
   */
  grpc.services.service3.StaffAvailabilityResult getResults(int index);
  /**
   * <code>repeated .service3.StaffAvailabilityResult results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .service3.StaffAvailabilityResult results = 1;</code>
   */
  java.util.List<? extends grpc.services.service3.StaffAvailabilityResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .service3.StaffAvailabilityResult results = 1;</code>
   */
  grpc.services.service3.StaffAvailabilityResultOrBuilder getResultsOrBuilder(
      int index);
}
