// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.schedule.Schedule staff_schedule = 1;</code>
   */
  boolean hasStaffSchedule();
  /**
   * <code>.schedule.Schedule staff_schedule = 1;</code>
   */
  grpc.services.schedule.Schedule getStaffSchedule();
  /**
   * <code>.schedule.Schedule staff_schedule = 1;</code>
   */
  grpc.services.schedule.ScheduleOrBuilder getStaffScheduleOrBuilder();
}
