// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_updated = 1;</code>
   */
  boolean getIsUpdated();

  /**
   * <code>.schedule.Schedule staff_schedule = 2;</code>
   */
  boolean hasStaffSchedule();
  /**
   * <code>.schedule.Schedule staff_schedule = 2;</code>
   */
  grpc.services.schedule.Schedule getStaffSchedule();
  /**
   * <code>.schedule.Schedule staff_schedule = 2;</code>
   */
  grpc.services.schedule.ScheduleOrBuilder getStaffScheduleOrBuilder();
}
