// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.services.service1;

public interface ScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  boolean hasSchedule();
  /**
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  grpc.services.schedule.Schedule getSchedule();
  /**
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder();
}
